# Generated by Django 4.0.5 on 2022-06-19 20:21

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('aadhar', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('panNum', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('postalAddress', models.CharField(max_length=255)),
                ('upiID', models.CharField(max_length=20)),
                ('whatsAppNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instagramHandle', models.CharField(max_length=30, null=True)),
                ('twitterHandle', models.CharField(max_length=30, null=True)),
                ('facebookHandle', models.CharField(max_length=30, null=True)),
                ('youtube', models.CharField(max_length=30, null=True)),
                ('linkedIn', models.CharField(max_length=30, null=True)),
                ('referenceCode', models.CharField(max_length=5, null=True)),
                ('birthDate', models.DateField()),
            ],
        ),
    ]
